### ISSUE TITLE
Take AWS credentials from for ~/.aws/credentials

### ISSUE THREAD

**Issue by jrwest** [rustyrazorblade/easy-cass-lab#23]
Instead of asking for them at runtime during `bin/easy-cass-lab init`

**Comment by jrwest** [comment]
or take them as environment variables

**Comment by rustyrazorblade** [comment]
Since terraform can read the AWS credentials file, I think you're right to want to use that.  We can avoid asking unnecessary questions.  A few thoughts:

* I think the concept of a easy-cass-lab profile should still exist, b/c we want to eventually support more than AWS.  
* If we take creds from the AWS config, file, we should ask which AWS profile we want to use.  I think it's going to be a common case that someone uses their main AWS creds for work and has an alternative for easy-cass-lab.
* While we're fixing this let's also fix #57 b/c it's been bugging me for a while and is a bit of a security hole.

**Comment by rustyrazorblade** [comment]
I've been thinking about this a bit more, and now i'm not so sure this is the right path.  I had originally built things with the intent of supporting multiple profiles which could be different cloud providers or even different accounts in the same provider.  

I think we need to keep this in place, but could optionally pre-populate during init with the values from `~/.aws/credentials`

**Comment by rustyrazorblade** [comment]
I'm closing this out in favor of using our own credentials system so we can support multiple profiles and cloud providers.
